### ISSUE TITLE
Feature Requests

### ISSUE THREAD

**Issue by oonqt** [bill-ahmed/qbit-material-WebUI#31]
Great UI, I am loving it so far, but I would like to see these features implemented:

* Ability to sort by progress
* Ability to sort by download/upload speed
* Ability to start a download with a magnet link as opposed to only having a torrent file upload option

I also found the following issues, mostly just me nitpicking, but nonetheless:

* Under the files tree, clicking the arrow doesn't expand the tree, you have to actually click on the element to expand the tree
![](https://i.memester.xyz/u/5sk.gif)

* Choose torrent file picker doesn't have any styling
![](https://i.memester.xyz/u/65c.png)

Thanks!

**Comment by bill-ahmed** [comment]
Hey there! Thanks for pointing out those out, i'll create some issues to keep track of the bugs/feature requests. The sorting by progress/download/upload speed should be pretty straight forward to do.

**Comment by bill-ahmed** [comment]
@oonqt The relevant issues have been resolved and closed. I've also moved all future builds from the `builds/` directory into the [releases page](https://github.com/bill-ahmed/qbit-material-WebUI/releases). Feel free to download the latest version there and try out magnet URLs.

If you find any more bugs/feature requests, please create the relevant issues for them. I'll be closing this one for now. Thanks!
