### ISSUE TITLE
Add log out button

### ISSUE THREAD

**Issue by overclockedllama** [bill-ahmed/qbit-material-WebUI#41]
Hi,

I really like this webui. Would it be possible to add a logout button?

Thanks

**Comment by overclockedllama** [comment]
I think this is the code to log out
```html
 <li class="divider"><a id="logoutLink"><img class="MyMenuIcon" alt="QBT_TR(Logout)QBT_TR[CONTEXT=HttpServer]" src="images/system-log-out.svg" width="16" height="16"/>QBT_TR(Logout)QBT_TR[CONTEXT=HttpServer]</a></li>
```

**Comment by bill-ahmed** [comment]
Yup, it certainly would be possible. The code above is specific to the original qBittorrent Web UI's implementation. This UI is written in Angular, so the process is going to be different.

I'll queue this for prioritization, feel free to keep a look-out on the progress.

**Comment by bill-ahmed** [comment]
@overclockedllama logout functionality is now there. If you encounter any bugs/features, please create the relevant issues for them. Thanks!

**Comment by overclockedllama** [comment]
Amazing, thank you!
