### ISSUE TITLE
Sort by Added On

### ISSUE THREAD

**Issue by jiznon** [bill-ahmed/qbit-material-WebUI#89]
**Is your feature request related to a problem? Please describe.**
Unable to sort by Added On.

**Describe the solution you'd like**
I would like to have the ability to sort by Added On, and ideally set this as a default.

**Additional context**
My typical use-case for a WebUI is to check on the status of my most recently added torrent(s) (whether added by the WebUI or automatically via sonarr, radarr, etc). I have been unable to find a way to accomplish this. That's the one thing holding back from using any of the handful of good looking WebUi I've seen. 

Thanks!

**Comment by bill-ahmed** [comment]
Yup I've been thinking of adding the option to customize fields such as which ones appear and their order. I'll update here once I have something basic working.

**Comment by bill-ahmed** [comment]
The column is now available in the [1.9.0 release](https://github.com/bill-ahmed/qbit-material-WebUI/releases/tag/v1.9.0) 🙂

**Comment by jiznon** [comment]
Thanks! Looks like some kinks with it:

Adding column under 'Columns To Display' add the Added On column, however clicking it's header does nothing but change the direction of the arrow. Refreshing doesn't resolve.

Choosing Added On under 'Default Sort Order' causes a completely empty torrent list.

Thanks for your time!

**Comment by bill-ahmed** [comment]
Yep I see the issue now, that was an oversight on my part. I overlooked the sorting aspect of the new columns...will push a quick fix for that.

Thanks for bringing it to my attention!

**Comment by bill-ahmed** [comment]
I've pushed the patched release [here](https://github.com/bill-ahmed/qbit-material-WebUI/releases/tag/v1.9.1). If you can confirm it is indeed working I'll go ahead and close this issue. Thanks!

**Comment by jiznon** [comment]
Both issues mentioned before are now resolved! I love it! Thanks again!
